# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Java配置
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64

# Maven镜像配置
systemProp.maven.repo.central=https://maven.aliyun.com/repository/central
systemProp.maven.repo.google=https://maven.aliyun.com/repository/google
systemProp.maven.repo.jcenter=https://maven.aliyun.com/repository/public
